pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

rootProject.name = 'eZWeight Forge'
//include "modules:1.16.5"
//include "modules:1.18.2"
//include "modules:1.19.2"
include "modules:1.20.1"
//include "modules:1.21.1"
//include "modules:1.21.3"
//include "modules:1.21.4"
//include "modules:1.21.5"
//include "modules:1.21.6"
//include "modules:1.21.7"
//include "modules:1.21.8"
//include "modules:1.21.9"
//include "modules:1.21.10"
//include "modules:1.21.11"